name: Performance Test

on: 
  workflow_dispatch:

jobs:
  performance_test:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run k6 scripts
        uses: grafana/k6-action@v0.3.0
        with: 
          filename: k6scripts/k6-basic-script.js
          flags: --vus 1 --iterations 1